#{{ if .Values.configMap.name }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: kube-system
data:
  DISPATCHER_MODE: {{ .Values.configMap.dispatcherMode }}
  EXTERNAL_DISPATCH: {{.Values.configMap.externalDispatch }}
  DISPATCHER_AGENT_CONFIGS: {{ .Values.configMap.agentConfigs }}
#{{ end }}
