apiVersion: workload.codeflare.dev/v1beta1
kind: AppWrapper
metadata:
  name: raycluster-glue
  namespace: default
spec:
  priority: 9
  resources:
    Items: []
    GenericItems:
    - replicas: 1
      custompodresources:
      - replicas: 2
        requests:
          cpu: 3
          memory: 16G
          nvidia.com/gpu: 1
        limits:
          cpu: 3
          memory: 16G
          nvidia.com/gpu: 1
      generictemplate:
        apiVersion: ray.io/v1alpha1
        kind: RayCluster
        metadata:
          labels:
            controller-tools.k8s.io: "1.0"
          name: glue-cluster
        spec:
          rayVersion: '1.12.0'
          headGroupSpec:
            serviceType: ClusterIP
            rayStartParams:
              dashboard-host: '0.0.0.0'
              block: 'true'
              num-gpus: '0'
            template:
              spec:
                containers:
                - name: ray-head
                  image: projectcodeflare/codeflare-glue:latest
                  env:
                  - name: AWS_ACCESS_KEY_ID
                    valueFrom:
                      secretKeyRef:
                        name: glue-s3-creds
                        key: AWS_ACCESS_KEY_ID
                  - name: AWS_SECRET_ACCESS_KEY
                    valueFrom:
                      secretKeyRef:
                        name: glue-s3-creds
                        key: AWS_SECRET_ACCESS_KEY
                  - name: ENDPOINT_URL
                    valueFrom:
                      secretKeyRef:
                        name: glue-s3-creds
                        key: ENDPOINT_URL
                  imagePullPolicy: Always
                  ports:
                  - containerPort: 6379
                    name: gcs
                  - containerPort: 8265
                    name: dashboard
                  - containerPort: 10001
                    name: client
                  lifecycle:
                    preStop:
                      exec:
                        command: ["/bin/sh","-c","ray stop"]
                  resources:
                    limits:
                      cpu: "2"
                      memory: "16G"
                      nvidia.com/gpu: "0"
                    requests:
                      cpu: "2"
                      memory: "16G"
                      nvidia.com/gpu: "0"
          workerGroupSpecs:
          - replicas: 1
            minReplicas: 1
            maxReplicas: 1
            groupName: small-group
            rayStartParams:
              block: 'true'
              num-gpus: '1'
            template:
              spec:
                initContainers:
                - name: init-myservice
                  image: busybox:1.28
                  command: ['sh', '-c', "until nslookup $RAY_IP.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
                containers:
                - name: ray-worker
                  image: projectcodeflare/codeflare-glue:latest
                  env:
                  - name: AWS_ACCESS_KEY_ID
                    valueFrom:
                      secretKeyRef:
                        name: glue-s3-creds
                        key: AWS_ACCESS_KEY_ID
                  - name: AWS_SECRET_ACCESS_KEY
                    valueFrom:
                      secretKeyRef:
                        name: glue-s3-creds
                        key: AWS_SECRET_ACCESS_KEY
                  - name: ENDPOINT_URL
                    valueFrom:
                      secretKeyRef:
                        name: glue-s3-creds
                        key: ENDPOINT_URL
                  lifecycle:
                    preStop:
                      exec:
                        command: ["/bin/sh","-c","ray stop"]
                  resources:
                    limits:
                      cpu: "4"
                      memory: "16G"
                      nvidia.com/gpu: "1"
                    requests:
                      cpu: "4"
                      memory: "16G"
                      nvidia.com/gpu: "1"
