apiVersion: mcad.ibm.com/v1beta1
kind: MCADHelmConfig
metadata:
  name: example-mcadhelmconfig
spec:
  # Default values copied from <project_dir>/helm-charts/mcad-controller/values.yaml
  
  configMap:
    agentConfigs: null
    dispatcherMode: "false"
    externalDispatch: "false"
    name: null
  deploymentName: xqueuejob-controller
  image:
    pullPolicy: Always
    repository: darroyo/mcad-controller
    tag: v1.29.0
  imagePullSecret:
    name: null
    password: dummyvalue
    registry: registry.stage1.ng.bluemix.net
    username: iamapikey
  loglevel: 4
  namespace: kube-system
  nodeSelector:
    hostname: null
  replicaCount: 1
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 2000m
      memory: 2048Mi
  serviceAccount: xqueuejob-controller
  volumes:
    hostPath: null
  
