#{{ if .Values.configMap.name }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: kube-system
data:
  DISPATCHER_MODE: {{ .Values.configMap.dispatcherMode | quote }}
  {{ if .Values.configMap.agentConfigs }}DISPATCHER_AGENT_CONFIGS: {{ .Values.configMap.agentConfigs }}{{ end }}
#{{ end }}
