# This workflow will build MCAD as well as build and push corresponding images

name: Build test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16

      - name: Install Dependencies
        run: |
          go get -u golang.org/x/lint/golint
          sudo apt install docker

      - name: Build and Push
        run: | 
          mkdir $GOPATH/src
          mkdir $GOPATH/src/github.com
          mkdir $GOPATH/src/github.com/project-codeflare
          cp -r . $GOPATH/src/github.com/project-codeflare/multi-cluster-app-dispatcher
          ll $GOPATH/src/github.com/project-codeflare/multi-cluster-app-dispatcher
          make mcad-controller
          make run-test
        env:
          GOPATH: /home/runner/go
          TEST_LOG_LEVEL: 4
