# This workflow will build MCAD as well as build and push corresponding images

name: Build test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Send Code to a Go-Compatible Dir
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: go/src/github.com/project-codeflare/multi-cluster-app-dispatcher

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16

      - name: Install Dependencies
        run: |
          go get -u golang.org/x/lint/golint
          sudo apt install docker

      - name: Build and Push
        run: | 
          export GOPATH=/home/runner/go
          export TEST_LOG_LEVEL=4
          make mcad-controller
          make run-test
